import { describe, test, expect } from "bun:test";
import { parseMarkdownToBlocks } from "./parser";

describe("parseMarkdownToBlocks — code fences", () => {
  /**
   * Baseline: the common triple-backtick fence still works after the nested-
   * fence fix. Regression guard so we don't break normal plans.
   */
  test("triple-backtick fence produces a single code block", () => {
    const md = "```js\nconsole.log('hi');\n```";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("code");
    expect(blocks[0].language).toBe("js");
    expect(blocks[0].content).toBe("console.log('hi');");
  });

  /**
   * A 4-backtick fence is used to embed a triple-backtick fence inside a code
   * block (e.g. showing a markdown example). Before the fix the inner ``` would
   * prematurely close the block, producing broken output.
   */
  test("4-backtick fence treats inner triple-backtick as content", () => {
    const md = "````md\n```js\ncode\n```\n````";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("code");
    expect(blocks[0].content).toBe("```js\ncode\n```");
  });

  /**
   * Ensure the language tag is still extracted correctly when the fence uses
   * more than three backticks.
   */
  test("4-backtick fence preserves language tag", () => {
    const md = "````markdown\nhello\n````";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].language).toBe("markdown");
  });

  /**
   * 5-backtick fence should allow both ``` and ```` lines as content,
   * only closing on a line of 5+ backticks.
   */
  test("5-backtick fence treats 3- and 4-backtick lines as content", () => {
    const md = "`````\n````\n```\n`````";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("code");
    expect(blocks[0].content).toBe("````\n```");
  });

  /**
   * A closing fence may have more backticks than the opener (CommonMark §4.5).
   * We support this so plans generated by tools that follow the spec parse
   * correctly.
   */
  test("closing fence with more backticks than opener still closes the block", () => {
    const md = "````\ncontent\n`````";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].content).toBe("content");
  });

  /**
   * Text before and after a nested-fence block must still parse into their own
   * blocks — the nested-fence fix must not swallow surrounding content.
   */
  test("nested-fence block does not swallow surrounding paragraphs", () => {
    const md = "intro\n\n````\n```\nnested\n```\n````\n\noutro";
    const blocks = parseMarkdownToBlocks(md);
    const types = blocks.map((b) => b.type);
    expect(types).toEqual(["paragraph", "code", "paragraph"]);
    expect(blocks[1].content).toBe("```\nnested\n```");
  });

  /**
   * An unclosed fence at end-of-file should produce a code block containing
   * whatever content was seen (CommonMark §4.5: unclosed fences extend to EOF).
   */
  test("unclosed fence at EOF produces a code block with seen content", () => {
    const md = "```js\nconst x = 1;";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("code");
    expect(blocks[0].language).toBe("js");
    expect(blocks[0].content).toBe("const x = 1;");
  });

  /**
   * A fence opener as the very last line of the document (no content, no
   * closing fence) should produce an empty code block rather than crashing.
   */
  test("fence opener as last line produces an empty code block", () => {
    const md = "```ts";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("code");
    expect(blocks[0].language).toBe("ts");
    expect(blocks[0].content).toBe("");
  });

  /**
   * Indented code fences (e.g. inside list items in a plan) must close when
   * the closing fence is equally indented. Before the fix, the closing fence
   * regex required backticks at column 0, so indented ``` never matched and
   * the code block swallowed everything to EOF.
   */
  test("indented closing fence closes the code block", () => {
    const md = "- Replace with reads:\n  ```ts\n  const x = 1;\n  ```\n- Next item";
    const blocks = parseMarkdownToBlocks(md);
    const types = blocks.map((b) => b.type);
    expect(types).toEqual(["list-item", "code", "list-item"]);
    expect(blocks[1].content).toBe("  const x = 1;");
    expect(blocks[2].content).toBe("Next item");
  });

  /**
   * A closing fence with trailing text (e.g. ``` some comment) should still
   * close the block. Before the fix, the regex required only whitespace after
   * backticks, so trailing text caused the fence to swallow everything to EOF.
   */
  test("closing fence with trailing text still closes the block", () => {
    const md = "```js\nconst x = 1;\n``` this is ignored\nafter";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(2);
    expect(blocks[0].type).toBe("code");
    expect(blocks[0].content).toBe("const x = 1;");
    expect(blocks[1].type).toBe("paragraph");
    expect(blocks[1].content).toBe("after");
  });

  test("deeply indented fence closes correctly", () => {
    const md = "    ```py\n    print('hi')\n    ```\nafter";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks[0].type).toBe("code");
    expect(blocks[0].language).toBe("py");
    expect(blocks[0].content).toBe("    print('hi')");
    expect(blocks[1].type).toBe("paragraph");
    expect(blocks[1].content).toBe("after");
  });
});

describe("parseMarkdownToBlocks — tables", () => {
  test("pipe-delimited table parses correctly", () => {
    const md = "| A | B |\n|---|---|\n| 1 | 2 |";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("table");
  });

  /**
   * Prose containing pipe characters (e.g. TypeScript union types in inline
   * code) must NOT be treated as a table. Before the fix, the regex
   * matched any line with 2+ pipes.
   */
  test("paragraph with inline code containing pipes is not a table", () => {
    const md = "The type is `'scroll' | 'wrap'` and supports `'a' | 'b' | 'c'` values.";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("paragraph");
    expect(blocks[0].content).toBe(md);
  });

  test("paragraph with multiple pipes in prose is not a table", () => {
    const md = "Use option A | B | C depending on context.";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("paragraph");
  });

  test("real-world plan: prose with union types is not a table", () => {
    const md = "`@pierre/diffs` supports `overflow: 'scroll' | 'wrap'` plus options, but Plannotator doesn't expose any of them.";
    const blocks = parseMarkdownToBlocks(md);
    expect(blocks).toHaveLength(1);
    expect(blocks[0].type).toBe("paragraph");
  });
});

describe("parseMarkdownToBlocks — real-world plan regression", () => {
  test("indented code fence inside list does not swallow rest of plan", () => {
    const md = [
      "### 5. Migrate App.tsx",
      "",
      "- **Remove** `useState` for `diffStyle`",
      "- **Replace** with ConfigStore reads:",
      "  ```ts",
      "  const diffStyle = useConfigValue('diffStyle');",
      "  ```",
      "- **Update** toolbar toggle handler",
      "",
      "### 6. Update DiffViewer",
    ].join("\n");
    const blocks = parseMarkdownToBlocks(md);
    const types = blocks.map((b) => b.type);
    expect(types).toEqual([
      "heading",      // ### 5. Migrate App.tsx
      "list-item",    // - **Remove**
      "list-item",    // - **Replace**
      "code",         // ```ts ... ```
      "list-item",    // - **Update**
      "heading",      // ### 6. Update DiffViewer
    ]);
    expect(blocks[3].type).toBe("code");
    expect(blocks[3].language).toBe("ts");
    expect(blocks[4].type).toBe("list-item");
    expect(blocks[5].type).toBe("heading");
  });
});
